### PR TITLE
Add new certificate to activate from July 1st 2024, 12:00 CEST

### PR DESCRIPTION
**Pull request by daanrijpkemacb**

### CODE REVIEW

**Comment by martijnhoutman** [comment]
Hi @daanrijpkemacb 

Thanks for this PR, this is indeed what we are looking for as well. Is there a plan to merge this PR before 2024-07-01, or do we need to revert to patching it until this has been merged and released?

**Comment by DaanRijpkema** [comment]
Hi @martijnhoutman yes I'm planning to do a minor release of this today as 2.3.2.9 (it will only serve as a minor change compared to the current latest release).
So you won't need to patch; I'll give you a heads-up!

**Comment by DaanRijpkema** [comment]
@martijnhoutman I've created a new release with this change as a minor release, see here: https://github.com/bluem-development/bluem-php/releases/tag/2.3.2.9b
Please let us know how the update & implementation goes!

(As the master is slightly ahead in commits, that is separate from this PR)

**Comment by martijnhoutman** [comment]
Thanks for this, will test ASAP!

**Comment by daanrijpkemacb** [comment]
As this code change is already live in 2.3.3 and in master, I'm closing this PR

**Pull request closed without merging**
